USE [base_monsanto]
GO

/****** Object:  Table [dbo].[CRITERIA]    Script Date: 08/08/2024 21:55:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOTIVO](
	[motivo] [varchar](500) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[type] [varchar](1) NULL,
 CONSTRAINT [PK__MOTIVO__3214EC271367E606] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOTIVO] ADD  CONSTRAINT [DF_MOTIVO_type]  DEFAULT (' ') FOR [type]
GO


